

--TOTAL EMPLOYEES
SELECT COUNT(*) AS TOTAL_EMPLOYEES
FROM HR_DATA;

--ATTRITION COUNT
SELECT COUNT(*) AS ATTRITION_COUNT
FROM HR_DATA
WHERE ATTRITION = 1;

--ATTRITION RATE
SELECT ROUND (
              SUM(CASE WHEN ATTRITION = 1 THEN 1 ELSE 0 END) * 100.0/COUNT(*), 2)
              AS ATTRITION_RATE
FROM HR_DATA;

--OVERTIME IMPACT ON ATTRITION
SELECT 
CASE 
    WHEN OVERTIME = 0 THEN 'NO'
    ELSE 'YES'
    END AS OVERTIME, 
       COUNT(*) AS EMPLOYEES,
       SUM(CASE WHEN ATTRITION = 1 THEN 1 ELSE 0 END) AS ATTRITION
FROM HR_DATA
GROUP BY OVERTIME
ORDER BY ATTRITION DESC;

--ATTRITION BY AGE GROUP
SELECT 
CASE 
    WHEN AGE BETWEEN 18 AND 25 THEN '18-25'
    WHEN AGE BETWEEN 25 AND 45 THEN '26-45'
    ELSE '46+'
    END AS AGE_GROUP,
COUNT(*) AS ATTRITION_COUNT
FROM HR_DATA    
WHERE ATTRITION = 1
GROUP BY
CASE
    WHEN AGE BETWEEN 18 AND 25 THEN '18-25'
    WHEN AGE BETWEEN 25 AND 45 THEN '26-45'
    ELSE '46+'
    END
ORDER BY ATTRITION_COUNT DESC;

--JOB SATISFACTION ANALYSIS
SELECT JOBSATISFACTION,COUNT(*) AS EMPLOYEES
FROM HR_DATA
GROUP BY JOBSATISFACTION
ORDER BY JOBSATISFACTION;

--ATTRITION BY JOBROLE
SELECT JOBROLE, COUNT(*) AS ATTRITION_COUNT
FROM HR_DATA
WHERE ATTRITION = 1
GROUP BY JOBROLE
ORDER BY ATTRITION_COUNT DESC;

--ATTRITION TREND BY TENURE
SELECT YEARSATCOMPANY,
       COUNT(*) AS EMPLOYEES,
       SUM(CAST(ATTRITION AS INT)) AS ATTRITION_COUNT
FROM HR_DATA
GROUP BY YEARSATCOMPANY
ORDER BY YEARSATCOMPANY;