

--ATTRITION BY DEPARTMENT
SELECT DEPARTMENT, COUNT(*) AS ATTRITION_COUNT
FROM HR_DATA
WHERE ATTRITION = 1
GROUP BY DEPARTMENT
ORDER BY ATTRITION_COUNT DESC;

--ATTRITION RATE BY DEPARTMENT
SELECT DEPARTMENT,
       COUNT(*) AS TOTAL_EMPLOYEE,
       SUM(CASE WHEN ATTRITION = 1 THEN 1 ELSE 0 END) AS ATTRITION_COUNT,
       ROUND(SUM(CASE WHEN ATTRITION = 1 THEN 1 ELSE 0 END) * 100.0/COUNT(*), 2) AS ATTRITION_RATE
FROM HR_DATA
GROUP BY DEPARTMENT
ORDER BY ATTRITION_RATE DESC;

--AVERAGE SALARY BY DEPARTMENT
SELECT DEPARTMENT, AVG(MONTHLYINCOME) AS AVG_SALARY
FROM HR_DATA
GROUP BY DEPARTMENT
ORDER BY AVG_SALARY DESC;

--ATTRITION BY INCOME
SELECT INCOME_GROUP AS INCOME, COUNT(*) AS ATTRITION_COUNT
FROM HR_DATA
WHERE ATTRITION = 1
GROUP BY INCOME_GROUP
ORDER BY ATTRITION_COUNT DESC;

--AVERAGE SALARY OF EMPLOYEES WHO LEFT
SELECT COUNT(*) AS EMPLOYEES,
       AVG(MONTHLYINCOME) AS AVG_SALARY
FROM HR_DATA
WHERE ATTRITION = 1;


--RANK EMPLOYEES BY SALARY WITHING DEPARTMENT
SELECT EMPLOYEENUMBER,
       DEPARTMENT,
       MONTHLYINCOME,
       DENSE_RANK() OVER(PARTITION BY DEPARTMENT ORDER BY MONTHLYINCOME DESC) AS SALARY_RANKING
FROM HR_DATA;

--EMPLOYEES EARNING ABOVE DEPARTMENT AVERAGE
SELECT EMPLOYEENUMBER,
       DEPARTMENT,
       MONTHLYINCOME
FROM HR_DATA H1
WHERE MONTHLYINCOME > (SELECT AVG(MONTHLYINCOME) AS AVG_SALARY
                FROM HR_DATA H2
                WHERE H1.DEPARTMENT = H2.DEPARTMENT);

--TOP 3 PAID EMPLOYEE PER DEPARTMENT
SELECT * 
FROM (
      SELECT EMPLOYEENUMBER,
             DEPARTMENT,
             MONTHLYINCOME,
             DENSE_RANK() OVER(PARTITION BY DEPARTMENT ORDER BY MONTHLYINCOME DESC) AS DRN
             FROM HR_DATA) T
WHERE DRN <= 3;